spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/druid?serverTimezone=CTT&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&tinyInt1isBit=false&multiStatementAllow=true
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5